#!/bin/sh

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

NAME=linux-headers
VERSION=4.9.11

PKG=${TMP}/package-${NAME}-${VERSION}

rm -rf $PKG
mkdir -p $PKG $OUT

cd $TMP
wget http://linux-libre.fsfla.org/pub/linux-libre/releases/${VERSION}-gnu/linux-libre-${VERSION}-gnu.tar.xz
tar xvfJ linux-libre-${VERSION}-gnu.tar.xz
cd linux-${VERSION}
make mrproper
make INSTALL_HDR_PATH=${PKG}/usr headers_install
find ${PKG}/usr \( -name .install -o -name ..install.cmd \) -delete

cd $PKG
makepkg -l prepend ${OUT}/${NAME}-${VERSION}.tlz

rm -rf $PKG $TMP
